---
- name: Puntos de montaje
  ansible.builtin.command:
    cmd: df -h
  register: salida_df
  changed_when: false


- name: Mostrar salida comando df -h
  ansible.builtin.debug:
    var: salida_df.stdout_lines


- name: Incluir tareas para Debian
  ansible.builtin.include_tasks: debian.yml

- name: Incluir tareas para CentOS
  ansible.builtin.include_tasks: centos.yml


...
