---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: CentOS
    image: docker.io/centos:latest
    pre_build_image: true
  - name: Debian
    image: docker.io/debian:latest
#    image: docker.io/ubuntu:latest
#    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
